audit_header: false
title: "Santa Fe's Best Real Estate Training"
description: Leland Titus, a top Real Estate Agent in Santa Fe, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: Leland Titus
  title:
  license_number:
  about_markdown: |
    Leland has been assisting Santa Fe home buyers and sellers for over ten years. He bought his first house at the age of 21 and fell in love with the process. Leland's passion for real estate has led him on a great journey that currently has him working as the Owner Broker of Santa Fe Realty Unlimited. Santa Fe Realty Unlimited is a small real estate office that believes in serving and helping its clients to accomplish their goals and needs. You the client are not just that a client but part of our family. This is a belief that Leland carries with him in every transaction, he will treat you as he would his own brother sister or mother. So for caring service and help with all your real estate needs please do not hesitate to give Leland Titus a call.
  market: Santa Fe
  brand: Santa Fe Realty Unlimited
  brokerage:
  address: 1486 South Saint Francis Drive<br>Santa Fe, NM 87505
  phone: 505-603-2435
  phone_type:
  phone2:
  phone2_type:
  email: nmrealtorleland@gmail.com
  url: http://www.SantaFeRealtyUltd.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Santa Fe Realty Unlimited can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/SantaFeRealtyRealEstate/
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UCYc9rPfukXDLBqB3652wD4A/
  twitter_url: https://twitter.com/SantaFeNMHouses
  instagram_url: https://www.instagram.com/santaferealty/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Santa Fe Real Estate Podcast with Leland Titus'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Santa Fe Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Santa Fe Realty Unlimited - your professional Santa Fe Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Santa Fe, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Leland Titus'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Santa Fe Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#231f20'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#231f20'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
